# Generated by Django 4.2.23 on 2025-07-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contracts",
            "0006_rename_days_to_gain_savedcontract_initial_days_to_gain_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
