# Generated by Django 4.2.23 on 2025-07-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0007_ticker"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedcontract",
            name="current_underlying_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedcontract",
            name="underlying_price_at_add",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
