# Generated by Django 4.2.23 on 2025-07-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0008_savedcontract_current_underlying_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedcontract",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="savedcontract",
            name="latest_simulation_result",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="savedcontract",
            name="initial_cost_per_contract",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="savedcontract",
            name="initial_days_to_gain",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
