# Generated by Django 4.2.23 on 2025-06-23 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("option_type", models.CharField(max_length=4)),
                ("strike", models.FloatField()),
                ("expiration", models.DateField()),
                ("premium", models.FloatField()),
                ("implied_volatility", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WatchlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("option_type", models.CharField(max_length=4)),
                ("strike", models.FloatField()),
                ("expiration", models.DateField()),
                ("days_to_gain", models.IntegerField()),
                ("number_of_contracts", models.IntegerField()),
                ("average_cost_per_contract", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScreenerInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("tickers", models.JSONField()),
                ("strike_pct", models.FloatField()),
                ("days_until_exp", models.IntegerField()),
                ("days_to_gain", models.IntegerField()),
                ("stock_gain_pct", models.FloatField()),
                ("allocation", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
