# Generated by Django 4.2.23 on 2025-07-08 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_alter_watchlistgroup_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedcontract",
            old_name="days_to_gain",
            new_name="initial_days_to_gain",
        ),
        migrations.AddField(
            model_name="savedcontract",
            name="first_added_to_group_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 7, 8, 20, 0, 47, 533360, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savedcontract",
            name="initial_cost_per_contract",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savedcontract",
            name="last_refresh_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="savedcontract",
            name="last_reset_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 7, 8, 20, 1, 51, 603983, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="savedcontract",
            name="average_cost_per_contract",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="savedcontract",
            name="number_of_contracts",
            field=models.IntegerField(default=1),
        ),
    ]
