# Generated by Django 4.2.23 on 2025-09-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_savedcontract_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcontract',
            name='initial_contracts_at_group_add',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedcontract',
            name='initial_equity_at_group_add',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedcontract',
            name='initial_underlying_at_group_add',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
