# Generated by Django 4.2.23 on 2025-09-24 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(blank=True, max_length=100)),
                ('tickers', models.JSONField()),
                ('analysis_types', models.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('total_tickers_analyzed', models.IntegerField(default=0)),
                ('session_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='WatchedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
                ('auto_analyze_fundamentals', models.BooleanField(default=True)),
                ('auto_analyze_eps_trends', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ticker'],
                'unique_together': {('user', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='StockFundamentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('all_time_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ath_percent_change', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('six_month_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recent_high_percent_change', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('five_year_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_pe', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('avg_5year_pe', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fair_value_ttm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fair_value_percent_change', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('avg_pe_fwd_eps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('macd_value', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('macd_signal', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('rsi_1year', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('live_price_time', models.DateTimeField(blank=True, null=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-analysis_date'],
                'unique_together': {('user', 'ticker', 'analysis_date')},
            },
        ),
        migrations.CreateModel(
            name='EPSTrendData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('curr_qtr_current', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('curr_qtr_7days', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('curr_qtr_30days', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('curr_qtr_60days', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('curr_qtr_90days', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('next_qtr_current', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('next_qtr_7days', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('next_qtr_30days', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('next_qtr_60days', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('next_qtr_90days', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('curr_yr_current', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('curr_yr_7days', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('curr_yr_30days', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('curr_yr_60days', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('curr_yr_90days', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('next_yr_current', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('next_yr_7days', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('next_yr_30days', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('next_yr_60days', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('next_yr_90days', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('curr_qtr_slope', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('next_qtr_slope', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('curr_yr_slope', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('next_yr_slope', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-analysis_date'],
                'unique_together': {('user', 'ticker', 'analysis_date')},
            },
        ),
    ]
