# Generated by Django 4.2.23 on 2025-08-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_savedcontract_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcontract',
            name='current_equity_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedcontract',
            name='current_premium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedcontract',
            name='initial_equity_invested',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedcontract',
            name='initial_premium',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
